spring.application.name=cinema2

secret.key=baejohnhynkangseulgisonseungwanparksoyoungkimyerimredvelvet
url.frontend=http://localhost:3000

spring.datasource.url=jdbc:postgresql://pg-shtven-shtven.f.aivencloud.com:28261/cinema?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_AZGCRQ6woC36HmNcGT1

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads

sendgrid.api.key=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
mail.from=shtvdanwill@gmail.com

cloudinary.cloud_name=dugeyulp7
cloudinary.api_key=165712875521846
cloudinary.api_secret=M2GpRkxr4y_wXMF86_067YkBlCQ
